using Ganss.Xss;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using System.Data;
using TraveLust.Data;
using TraveLust.Models;

namespace TraveLust.Controllers
{
    public class GroupchatsController : Controller
    {
        private readonly ApplicationDbContext db;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public GroupchatsController(
        ApplicationDbContext context,
        UserManager<ApplicationUser> userManager,
        RoleManager<IdentityRole> roleManager
        )
        {
            db = context;
            _userManager = userManager;
            _roleManager = roleManager;
        }

        // index page displays all groupchats of current user
        public IActionResult Index()
        {
            IQueryable<Groupchat> groupchats = db.Groupchats.Include("UserInGroupchats")
                .Include("Creator")
                .Where(g => g.UserInGroupchats.Any(u => u.UserId == _userManager.GetUserId(User)));

            ViewBag.Groupchats = groupchats;

            if (TempData.ContainsKey("message"))
            {
                ViewBag.Message = TempData["message"];
            }

            return View();
        }

        // creating a new groupchat
        public IActionResult New()
        {
            /*generated by GitHub Copilot*/
            Groupchat groupchat = new Groupchat();
            
            return View(groupchat);
        }

        [HttpPost]
        public async Task<IActionResult> New(Groupchat groupchat)
        {
            groupchat.CreatorId = _userManager.GetUserId(User);


            var sanitizer = new HtmlSanitizer();

            if (ModelState.IsValid)
            {
                groupchat.Description = sanitizer.Sanitize(groupchat.Description);
                

                db.Groupchats.Add(groupchat);

                db.SaveChanges();

                UserInGroupchat userInGroupchat = new UserInGroupchat();
                userInGroupchat.UserId = _userManager.GetUserId(User);
                userInGroupchat.GroupchatId = groupchat.GroupchatId;
                db.UserInGroupchats.Add(userInGroupchat);

                db.SaveChanges();
                TempData["message"] = "Groupchat created!";

                return RedirectToAction("AddFriends", new {groupchatId = groupchat.GroupchatId } );
            }
            else
            {
                return View(groupchat);
            }
        }

        // adding users to a groupchat
        public ActionResult AddFriends(int groupchatId)
        {
            Groupchat groupchat = db.Groupchats.Include("UserInGroupchats").Where(g => g.GroupchatId == groupchatId).First();
            groupchat.AllUsers = GetAllUsers();

            if (TempData.ContainsKey("message"))
            {
                ViewBag.Message = TempData["message"];
            }

            return View(groupchat);
        }

        [NonAction]
        public IEnumerable<SelectListItem> GetAllUsers()
        {
            var selectList = new List<SelectListItem>();

            var users = db.Users.Where(u => u.Id != _userManager.GetUserId(User));

            foreach (var user in users)
            {
                selectList.Add(new SelectListItem
                {
                    Value = user.Id.ToString(),
                    Text = user.UserName.ToString()
                });
            }
            return selectList;
        }
    }
}
