using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using System.Data;
using TraveLust.Data;
using TraveLust.Data.Migrations;
using TraveLust.Models;

namespace TraveLust.Controllers
{
    public class MessagesController : Controller
    {
        private readonly ApplicationDbContext db;
        private readonly UserManager<ApplicationUser> _userManager;
        private readonly RoleManager<IdentityRole> _roleManager;

        public MessagesController(ApplicationDbContext context, UserManager<ApplicationUser> userManager,
            RoleManager<IdentityRole> roleManager)
        {
            db = context;
            _userManager = userManager;
            _roleManager = roleManager;
        }

        //sending a message
        //generated by GitHub Copilot
        [Authorize(Roles = "User")]
        public IActionResult New(Message message)
        {
            message.Date = DateTime.Now;
            message.UserId = _userManager.GetUserId(User);
            if (ModelState.IsValid)
            {
                db.Messages.Add(message);
                db.SaveChanges();
                return RedirectToAction("Index", "Groupchats", new { id1 = message.GroupchatId });
            }
            else
            {
                return RedirectToAction("Index", "Groupchats", new { id1 = message.GroupchatId });
            }
        }

    }
}
