using Microsoft.AspNetCore.Authorization;
using System.Data;
using Microsoft.AspNetCore.Mvc;
using TraveLust.Data;
using TraveLust.Models;

namespace TraveLust.Controllers
{
    public class VotesController : Controller
    {
        private readonly ApplicationDbContext db;

        public VotesController(ApplicationDbContext context)
        {
            db = context;
        }

        [HttpPost]
        public ActionResult New(Vote vote)
        {
            // code generated by GitHub Copilot
            db.Votes.Add(vote);
            db.SaveChanges();

            Itinerary itinerary = db.Itineraries.Find(vote.ItineraryId);
            Groupchat groupchat = db.Groupchats.Where(g => g.ItineraryId == itinerary.ItineraryId).FirstOrDefault();

            return RedirectToAction("Index", "Groupchats", new { id1 =  groupchat.GroupchatId, id2 = itinerary.ItineraryId});
        }

        [HttpPost]
        public IActionResult Delete(Vote vote)
        {
            db.Votes.Remove(vote);
            db.SaveChanges();

            Itinerary itinerary = db.Itineraries.Find(vote.ItineraryId);
            Groupchat groupchat = db.Groupchats.Where(g => g.ItineraryId == itinerary.ItineraryId).FirstOrDefault();

            return RedirectToAction("Index", "Groupchats", new { id1 = groupchat.GroupchatId, id2 = itinerary.ItineraryId });
        }
    }
}
