using Microsoft.AspNetCore.Mvc.Rendering;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace TraveLust.Models
{
    public class Message
    {
        //generated by GitHub Copilot
        [Key]
        public int MessageId { get; set; }

        public string? UserId { get; set; }
        public virtual ApplicationUser? User { get; set; }

        public int? GroupchatId { get; set; }
        public virtual Groupchat? Groupchat { get; set; }

        public DateTime Date { get; set; }

        public string Text { get; set; }
    }
}
